-- 02_streams.sql
-- Snowflake Streams for event-driven processing

USE DATABASE CLAUDE_LOGS;
USE SCHEMA ACTIVITIES;

-- Stream on main activity table for real-time processing
CREATE STREAM IF NOT EXISTS S_CLAUDE_STREAM 
    ON TABLE CLAUDE_STREAM
    APPEND_ONLY = FALSE;

-- Stream on insight atoms for aggregation
CREATE STREAM IF NOT EXISTS S_INSIGHT_ATOMS
    ON TABLE INSIGHT_ATOMS
    APPEND_ONLY = FALSE;

-- Stream on context cache for change tracking
CREATE STREAM IF NOT EXISTS S_CONTEXT_CACHE
    ON TABLE CONTEXT_CACHE
    APPEND_ONLY = FALSE;

-- Stream for security events
CREATE STREAM IF NOT EXISTS S_SECURITY_AUDIT
    ON TABLE SECURITY_AUDIT_LOG
    APPEND_ONLY = TRUE;

-- Enable change tracking on source tables
ALTER TABLE CLAUDE_STREAM SET CHANGE_TRACKING = TRUE;
ALTER TABLE INSIGHT_ATOMS SET CHANGE_TRACKING = TRUE;
ALTER TABLE CONTEXT_CACHE SET CHANGE_TRACKING = TRUE;
ALTER TABLE SECURITY_AUDIT_LOG SET CHANGE_TRACKING = TRUE;

-- Grant permissions on streams
GRANT SELECT ON ALL STREAMS IN SCHEMA ACTIVITIES TO ROLE PUBLIC;